version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "coverage"
      - dependency-name: "fastapi"
      - dependency-name: "httpx"
      - dependency-name: "pydantic"
      - dependency-name: "starlette"
      - dependency-name: "uvicorn"

  - package-ecosystem: docker
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
